//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCourseComment
    {
        public tblCourseComment()
        {
            this.tblCourseComment1 = new HashSet<tblCourseComment>();
        }
    
        public int CourseCommentID { get; set; }
        public int UserID { get; set; }
        public string CommentContent { get; set; }
        public System.DateTime AddedDate { get; set; }
        public int CourseID { get; set; }
        public int CourseCommentStatusID { get; set; }
        public int AnsweredCommentID { get; set; }
    
        public virtual ICollection<tblCourseComment> tblCourseComment1 { get; set; }
        public virtual tblCourseComment tblCourseComment2 { get; set; }
        public virtual tblCourseCommentStatus tblCourseCommentStatus { get; set; }
        public virtual tblCourses tblCourses { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
