//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCourseKeywords
    {
        public int CourseKeywordsID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> CourseKeywordID { get; set; }
    
        public virtual tblCourseKeyword tblCourseKeyword { get; set; }
        public virtual tblCourses tblCourses { get; set; }
    }
}
