//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCountries
    {
        public tblCountries()
        {
            this.tblProvinces = new HashSet<tblProvinces>();
            this.tblUniversities = new HashSet<tblUniversities>();
        }
    
        public int CountryID { get; set; }
        public string CountryName { get; set; }
    
        public virtual ICollection<tblProvinces> tblProvinces { get; set; }
        public virtual ICollection<tblUniversities> tblUniversities { get; set; }
    }
}
