//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompanies
    {
        public tblCompanies()
        {
            this.tblJobs = new HashSet<tblJobs>();
            this.tblProjectAds = new HashSet<tblProjectAds>();
        }
    
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public System.DateTime CompanyDate { get; set; }
        public string CompanyAbout { get; set; }
        public int UserID { get; set; }
    
        public virtual tblUsers tblUsers { get; set; }
        public virtual ICollection<tblJobs> tblJobs { get; set; }
        public virtual ICollection<tblProjectAds> tblProjectAds { get; set; }
        public virtual tblProjectApplications tblProjectApplications { get; set; }
    }
}
