//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCourses
    {
        public tblCourses()
        {
            this.tblCourseComment = new HashSet<tblCourseComment>();
            this.tblCourseKeywords = new HashSet<tblCourseKeywords>();
            this.tblCourseRate = new HashSet<tblCourseRate>();
            this.tblLesson = new HashSet<tblLesson>();
            this.tblUsersCourses = new HashSet<tblUsersCourses>();
        }
    
        public int CourseID { get; set; }
        public string Title { get; set; }
        public int UserID { get; set; }
        public int CategoryID { get; set; }
        public string Description { get; set; }
        public int CourseLevelID { get; set; }
        public int CourseStatusID { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string Image { get; set; }
        public string YoutubeURL { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        public virtual ICollection<tblCourseComment> tblCourseComment { get; set; }
        public virtual ICollection<tblCourseKeywords> tblCourseKeywords { get; set; }
        public virtual tblCourseLevel tblCourseLevel { get; set; }
        public virtual ICollection<tblCourseRate> tblCourseRate { get; set; }
        public virtual tblCourseStatus tblCourseStatus { get; set; }
        public virtual ICollection<tblLesson> tblLesson { get; set; }
        public virtual ICollection<tblUsersCourses> tblUsersCourses { get; set; }
    }
}
