//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCourseLevel
    {
        public tblCourseLevel()
        {
            this.tblCourses = new HashSet<tblCourses>();
        }
    
        public int CourseLevelID { get; set; }
        public string CourseLevel { get; set; }
    
        public virtual ICollection<tblCourses> tblCourses { get; set; }
    }
}
