//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategory
    {
        public tblCategory()
        {
            this.tblCategory1 = new HashSet<tblCategory>();
            this.tblCourses = new HashSet<tblCourses>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> ParentCategoryID { get; set; }
    
        public virtual ICollection<tblCategory> tblCategory1 { get; set; }
        public virtual tblCategory tblCategory2 { get; set; }
        public virtual ICollection<tblCourses> tblCourses { get; set; }
    }
}
