//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDisabledStatus
    {
        public tblDisabledStatus()
        {
            this.tblJobsDisabled = new HashSet<tblJobsDisabled>();
            this.tblProfiles = new HashSet<tblProfiles>();
        }
    
        public int DisabledID { get; set; }
        public string DisabledName { get; set; }
    
        public virtual ICollection<tblJobsDisabled> tblJobsDisabled { get; set; }
        public virtual ICollection<tblProfiles> tblProfiles { get; set; }
    }
}
