//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFaculties
    {
        public tblFaculties()
        {
            this.tblSections = new HashSet<tblSections>();
        }
    
        public int FacultyID { get; set; }
        public string FacultyName { get; set; }
        public int UniversityID { get; set; }
    
        public virtual tblUniversities tblUniversities { get; set; }
        public virtual ICollection<tblSections> tblSections { get; set; }
    }
}
