//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFollowing
    {
        public tblFollowing()
        {
            this.tblNotifications = new HashSet<tblNotifications>();
        }
    
        public int FollowingID { get; set; }
        public int UserID { get; set; }
        public int FollowingUserID { get; set; }
        public Nullable<System.DateTime> FollowDate { get; set; }
    
        public virtual tblUsers tblUsers { get; set; }
        public virtual ICollection<tblNotifications> tblNotifications { get; set; }
    }
}
