//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInterView
    {
        public tblInterView()
        {
            this.tblInterViewAnswers = new HashSet<tblInterViewAnswers>();
        }
    
        public int InterviewID { get; set; }
        public string InterviewQues { get; set; }
        public Nullable<int> JobID { get; set; }
    
        public virtual tblJobs tblJobs { get; set; }
        public virtual ICollection<tblInterViewAnswers> tblInterViewAnswers { get; set; }
    }
}
