//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJobs
    {
        public tblJobs()
        {
            this.tblInterView = new HashSet<tblInterView>();
            this.tblJobApplications = new HashSet<tblJobApplications>();
            this.tblJobOperationType = new HashSet<tblJobOperationType>();
            this.tblJobsDepartment = new HashSet<tblJobsDepartment>();
            this.tblJobsDisabled = new HashSet<tblJobsDisabled>();
            this.tblJobsSkils = new HashSet<tblJobsSkils>();
            this.tblJobsEducationLevel = new HashSet<tblJobsEducationLevel>();
        }
    
        public int JobID { get; set; }
        public int CompanyID { get; set; }
        public int WorksPositionID { get; set; }
        public int SectorID { get; set; }
        public string QualificationsText { get; set; }
        public string JobDescription { get; set; }
        public int DistrictID { get; set; }
        public Nullable<System.DateTime> JobStartDate { get; set; }
        public bool JobStatu { get; set; }
        public Nullable<int> PersonelNumber { get; set; }
        public Nullable<System.DateTime> JobFinishDate { get; set; }
    
        public virtual tblCompanies tblCompanies { get; set; }
        public virtual tblDistricts tblDistricts { get; set; }
        public virtual ICollection<tblInterView> tblInterView { get; set; }
        public virtual ICollection<tblJobApplications> tblJobApplications { get; set; }
        public virtual ICollection<tblJobOperationType> tblJobOperationType { get; set; }
        public virtual tblSectors tblSectors { get; set; }
        public virtual tblWorksPosition tblWorksPosition { get; set; }
        public virtual ICollection<tblJobsDepartment> tblJobsDepartment { get; set; }
        public virtual ICollection<tblJobsDisabled> tblJobsDisabled { get; set; }
        public virtual ICollection<tblJobsSkils> tblJobsSkils { get; set; }
        public virtual ICollection<tblJobsEducationLevel> tblJobsEducationLevel { get; set; }
    }
}
