//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJobsDisabled
    {
        public int JobsDisabledID { get; set; }
        public int JobID { get; set; }
        public int DisabledID { get; set; }
    
        public virtual tblDisabledStatus tblDisabledStatus { get; set; }
        public virtual tblJobs tblJobs { get; set; }
    }
}
