//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJobsDepartment
    {
        public int JobsDepartment { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> JobID { get; set; }
    
        public virtual tblDepartments tblDepartments { get; set; }
        public virtual tblJobs tblJobs { get; set; }
    }
}
