//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLesson
    {
        public int LessonID { get; set; }
        public string Title { get; set; }
        public System.DateTime AddedDate { get; set; }
        public int CourseID { get; set; }
        public int VideoDuration { get; set; }
        public string VideoLink { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    
        public virtual tblCourses tblCourses { get; set; }
    }
}
