//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotifications
    {
        public int NotificationID { get; set; }
        public System.DateTime NotificationDate { get; set; }
        public bool NotificationSeen { get; set; }
        public int UserID { get; set; }
        public Nullable<int> SharesCommentID { get; set; }
        public Nullable<int> SharesLikeID { get; set; }
        public Nullable<int> QuestionLikeAndDislikeID { get; set; }
        public Nullable<int> QuestionAnserwsID { get; set; }
        public Nullable<int> QuestionAnwersAndDislikeID { get; set; }
        public Nullable<int> FollowRequestID { get; set; }
        public Nullable<int> FollowingID { get; set; }
        public Nullable<int> SkillsValidationID { get; set; }
        public Nullable<int> ProjectApplicationID { get; set; }
    
        public virtual tblFollowing tblFollowing { get; set; }
        public virtual tblFollowRequest tblFollowRequest { get; set; }
        public virtual tblProjectApplications tblProjectApplications { get; set; }
        public virtual tblQuestionAnswers tblQuestionAnswers { get; set; }
        public virtual tblQuestionAnwersAndDislike tblQuestionAnwersAndDislike { get; set; }
        public virtual tblQuestionLikeAndDislike tblQuestionLikeAndDislike { get; set; }
        public virtual tblSharesComment tblSharesComment { get; set; }
        public virtual tblSharesLike tblSharesLike { get; set; }
        public virtual tblSkillsValidation tblSkillsValidation { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
