//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProfiles
    {
        public int ProfileID { get; set; }
        public int UserID { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<System.DateTime> Birtdate { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string AboutMe { get; set; }
        public Nullable<int> DisabledID { get; set; }
        public Nullable<double> DisabledValue { get; set; }
        public string Avatar { get; set; }
        public string Adress { get; set; }
        public string ChatStatus { get; set; }
        public string Title { get; set; }
        public Nullable<bool> ProfilePrivacy { get; set; }
    
        public virtual tblDisabledStatus tblDisabledStatus { get; set; }
        public virtual tblDistricts tblDistricts { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
