//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonelEducationType
    {
        public tblPersonelEducationType()
        {
            this.tblJobsEducationLevel = new HashSet<tblJobsEducationLevel>();
            this.tblPersonelEducation = new HashSet<tblPersonelEducation>();
        }
    
        public int PersonelEducationTypeID { get; set; }
        public string PersonelEducationTypeName { get; set; }
    
        public virtual ICollection<tblJobsEducationLevel> tblJobsEducationLevel { get; set; }
        public virtual ICollection<tblPersonelEducation> tblPersonelEducation { get; set; }
    }
}
