//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectApplications
    {
        public tblProjectApplications()
        {
            this.tblNotifications = new HashSet<tblNotifications>();
        }
    
        public int ProjectApplicationID { get; set; }
        public System.DateTime ProjectApplicationDate { get; set; }
        public double MinMoney { get; set; }
        public double MaxMoney { get; set; }
        public int ProjectAwardID { get; set; }
        public bool Projectstatus { get; set; }
    
        public virtual tblCompanies tblCompanies { get; set; }
        public virtual ICollection<tblNotifications> tblNotifications { get; set; }
        public virtual tblProjectAds tblProjectAds { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
