//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectAds
    {
        public tblProjectAds()
        {
            this.tblProjectApplications = new HashSet<tblProjectApplications>();
        }
    
        public int ProjectAwardID { get; set; }
        public int ProjectSenderID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectAbout { get; set; }
        public System.DateTime ProjectDate { get; set; }
        public bool ProjectState { get; set; }
    
        public virtual tblCompanies tblCompanies { get; set; }
        public virtual tblUsers tblUsers { get; set; }
        public virtual ICollection<tblProjectApplications> tblProjectApplications { get; set; }
    }
}
