//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestions
    {
        public tblQuestions()
        {
            this.tblQuestionAnswers = new HashSet<tblQuestionAnswers>();
            this.tblQuestionLikeAndDislike = new HashSet<tblQuestionLikeAndDislike>();
            this.tblTags = new HashSet<tblTags>();
        }
    
        public int QuestionID { get; set; }
        public string QuestionTitle { get; set; }
        public string QuestionText { get; set; }
        public int UserID { get; set; }
        public int SubjectID { get; set; }
        public string QuestionImage { get; set; }
    
        public virtual ICollection<tblQuestionAnswers> tblQuestionAnswers { get; set; }
        public virtual tblQuestionAreaType tblQuestionAreaType { get; set; }
        public virtual ICollection<tblQuestionLikeAndDislike> tblQuestionLikeAndDislike { get; set; }
        public virtual ICollection<tblTags> tblTags { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
