//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestionLikeAndDislike
    {
        public tblQuestionLikeAndDislike()
        {
            this.tblNotifications = new HashSet<tblNotifications>();
        }
    
        public int QuestionLikeAndDislikeID { get; set; }
        public int QuestionID { get; set; }
        public int UserID { get; set; }
        public Nullable<bool> QuestionLike { get; set; }
    
        public virtual ICollection<tblNotifications> tblNotifications { get; set; }
        public virtual tblQuestions tblQuestions { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
