//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuestionAnwersAndDislike
    {
        public tblQuestionAnwersAndDislike()
        {
            this.tblNotifications = new HashSet<tblNotifications>();
        }
    
        public int QuestionAnwersAndDislikeID { get; set; }
        public int QuestionAnserwsID { get; set; }
        public int UsersID { get; set; }
        public Nullable<bool> QuestionAnserwsLike { get; set; }
    
        public virtual ICollection<tblNotifications> tblNotifications { get; set; }
        public virtual tblQuestionAnswers tblQuestionAnswers { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
