//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSections
    {
        public tblSections()
        {
            this.tblPersonelEducation = new HashSet<tblPersonelEducation>();
        }
    
        public int SectionID { get; set; }
        public string SectionName { get; set; }
        public int FacultyID { get; set; }
    
        public virtual tblFaculties tblFaculties { get; set; }
        public virtual ICollection<tblPersonelEducation> tblPersonelEducation { get; set; }
    }
}
