//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSectors
    {
        public tblSectors()
        {
            this.tblJobs = new HashSet<tblJobs>();
        }
    
        public int SectorID { get; set; }
        public string SectorName { get; set; }
    
        public virtual ICollection<tblJobs> tblJobs { get; set; }
    }
}
