//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUniversities
    {
        public tblUniversities()
        {
            this.tblFaculties = new HashSet<tblFaculties>();
        }
    
        public int UniversityID { get; set; }
        public string UniversityName { get; set; }
        public int CountryID { get; set; }
    
        public virtual tblCountries tblCountries { get; set; }
        public virtual ICollection<tblFaculties> tblFaculties { get; set; }
    }
}
