//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorks
    {
        public tblWorks()
        {
            this.tblOldProject = new HashSet<tblOldProject>();
        }
    
        public int WorkID { get; set; }
        public string PersonelJobName { get; set; }
        public System.DateTime PersonelJobStartDate { get; set; }
        public Nullable<System.DateTime> PersonelJobFinishDate { get; set; }
        public int UserID { get; set; }
        public int WorksPositionID { get; set; }
        public Nullable<bool> WorksActive { get; set; }
    
        public virtual ICollection<tblOldProject> tblOldProject { get; set; }
        public virtual tblWorksPosition tblWorksPosition { get; set; }
    }
}
