//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSQA.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorksPosition
    {
        public tblWorksPosition()
        {
            this.tblJobs = new HashSet<tblJobs>();
            this.tblWorks = new HashSet<tblWorks>();
        }
    
        public int WorksPositionID { get; set; }
        public string WorksPositionName { get; set; }
    
        public virtual ICollection<tblJobs> tblJobs { get; set; }
        public virtual ICollection<tblWorks> tblWorks { get; set; }
    }
}
