//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAQ.ServiceReferansimiz2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelNumberField;
        
        private int UserTypeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserSurname {
            get {
                return this.UserSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserSurnameField, value) != true)) {
                    this.UserSurnameField = value;
                    this.RaisePropertyChanged("UserSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UserPassword {
            get {
                return this.UserPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPasswordField, value) != true)) {
                    this.UserPasswordField = value;
                    this.RaisePropertyChanged("UserPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TelNumber {
            get {
                return this.TelNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TelNumberField, value) != true)) {
                    this.TelNumberField = value;
                    this.RaisePropertyChanged("TelNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int UserTypeID {
            get {
                return this.UserTypeIDField;
            }
            set {
                if ((this.UserTypeIDField.Equals(value) != true)) {
                    this.UserTypeIDField = value;
                    this.RaisePropertyChanged("UserTypeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LoginData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserPassword {
            get {
                return this.UserPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPasswordField, value) != true)) {
                    this.UserPasswordField = value;
                    this.RaisePropertyChanged("UserPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Questions", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Questions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int QuestionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionTextField;
        
        private int UserIDField;
        
        private int SubjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionImageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int QuestionID {
            get {
                return this.QuestionIDField;
            }
            set {
                if ((this.QuestionIDField.Equals(value) != true)) {
                    this.QuestionIDField = value;
                    this.RaisePropertyChanged("QuestionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string QuestionTitle {
            get {
                return this.QuestionTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionTitleField, value) != true)) {
                    this.QuestionTitleField = value;
                    this.RaisePropertyChanged("QuestionTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string QuestionText {
            get {
                return this.QuestionTextField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionTextField, value) != true)) {
                    this.QuestionTextField = value;
                    this.RaisePropertyChanged("QuestionText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int SubjectID {
            get {
                return this.SubjectIDField;
            }
            set {
                if ((this.SubjectIDField.Equals(value) != true)) {
                    this.SubjectIDField = value;
                    this.RaisePropertyChanged("SubjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string QuestionImage {
            get {
                return this.QuestionImageField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionImageField, value) != true)) {
                    this.QuestionImageField = value;
                    this.RaisePropertyChanged("QuestionImage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestionAnswers", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class QuestionAnswers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int QuestionAnserwsIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnswerTextField;
        
        private int AnswerUserIDField;
        
        private int AccuracyField;
        
        private int QuestionIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int QuestionAnserwsID {
            get {
                return this.QuestionAnserwsIDField;
            }
            set {
                if ((this.QuestionAnserwsIDField.Equals(value) != true)) {
                    this.QuestionAnserwsIDField = value;
                    this.RaisePropertyChanged("QuestionAnserwsID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AnswerText {
            get {
                return this.AnswerTextField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswerTextField, value) != true)) {
                    this.AnswerTextField = value;
                    this.RaisePropertyChanged("AnswerText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int AnswerUserID {
            get {
                return this.AnswerUserIDField;
            }
            set {
                if ((this.AnswerUserIDField.Equals(value) != true)) {
                    this.AnswerUserIDField = value;
                    this.RaisePropertyChanged("AnswerUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Accuracy {
            get {
                return this.AccuracyField;
            }
            set {
                if ((this.AccuracyField.Equals(value) != true)) {
                    this.AccuracyField = value;
                    this.RaisePropertyChanged("Accuracy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int QuestionID {
            get {
                return this.QuestionIDField;
            }
            set {
                if ((this.QuestionIDField.Equals(value) != true)) {
                    this.QuestionIDField = value;
                    this.RaisePropertyChanged("QuestionID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferansimiz2.AQServiceSoap")]
    public interface AQServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        MVCAQ.ServiceReferansimiz2.HelloWorldResponse HelloWorld(MVCAQ.ServiceReferansimiz2.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.HelloWorldResponse> HelloWorldAsync(MVCAQ.ServiceReferansimiz2.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name u from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Kaydol", ReplyAction="*")]
        MVCAQ.ServiceReferansimiz2.KaydolResponse Kaydol(MVCAQ.ServiceReferansimiz2.KaydolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Kaydol", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.KaydolResponse> KaydolAsync(MVCAQ.ServiceReferansimiz2.KaydolRequest request);
        
        // CODEGEN: Generating message contract since element name d from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GirisYap", ReplyAction="*")]
        MVCAQ.ServiceReferansimiz2.GirisYapResponse GirisYap(MVCAQ.ServiceReferansimiz2.GirisYapRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GirisYap", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.GirisYapResponse> GirisYapAsync(MVCAQ.ServiceReferansimiz2.GirisYapRequest request);
        
        // CODEGEN: Generating message contract since element name q from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SoruSor", ReplyAction="*")]
        MVCAQ.ServiceReferansimiz2.SoruSorResponse SoruSor(MVCAQ.ServiceReferansimiz2.SoruSorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SoruSor", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.SoruSorResponse> SoruSorAsync(MVCAQ.ServiceReferansimiz2.SoruSorRequest request);
        
        // CODEGEN: Generating message contract since element name SoruSilResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SoruSil", ReplyAction="*")]
        MVCAQ.ServiceReferansimiz2.SoruSilResponse SoruSil(MVCAQ.ServiceReferansimiz2.SoruSilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SoruSil", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.SoruSilResponse> SoruSilAsync(MVCAQ.ServiceReferansimiz2.SoruSilRequest request);
        
        // CODEGEN: Generating message contract since element name SoruListeleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SoruListele", ReplyAction="*")]
        MVCAQ.ServiceReferansimiz2.SoruListeleResponse SoruListele(MVCAQ.ServiceReferansimiz2.SoruListeleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SoruListele", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.SoruListeleResponse> SoruListeleAsync(MVCAQ.ServiceReferansimiz2.SoruListeleRequest request);
        
        // CODEGEN: Generating message contract since element name s from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SoruAra", ReplyAction="*")]
        MVCAQ.ServiceReferansimiz2.SoruAraResponse SoruAra(MVCAQ.ServiceReferansimiz2.SoruAraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SoruAra", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.SoruAraResponse> SoruAraAsync(MVCAQ.ServiceReferansimiz2.SoruAraRequest request);
        
        // CODEGEN: Generating message contract since element name q from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SoruDuzenle", ReplyAction="*")]
        MVCAQ.ServiceReferansimiz2.SoruDuzenleResponse SoruDuzenle(MVCAQ.ServiceReferansimiz2.SoruDuzenleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SoruDuzenle", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.SoruDuzenleResponse> SoruDuzenleAsync(MVCAQ.ServiceReferansimiz2.SoruDuzenleRequest request);
        
        // CODEGEN: Generating message contract since element name q from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SoruCevapla", ReplyAction="*")]
        MVCAQ.ServiceReferansimiz2.SoruCevaplaResponse SoruCevapla(MVCAQ.ServiceReferansimiz2.SoruCevaplaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SoruCevapla", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.SoruCevaplaResponse> SoruCevaplaAsync(MVCAQ.ServiceReferansimiz2.SoruCevaplaRequest request);
        
        // CODEGEN: Generating message contract since element name CevaplariGosterResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CevaplariGoster", ReplyAction="*")]
        MVCAQ.ServiceReferansimiz2.CevaplariGosterResponse CevaplariGoster(MVCAQ.ServiceReferansimiz2.CevaplariGosterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CevaplariGoster", ReplyAction="*")]
        System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.CevaplariGosterResponse> CevaplariGosterAsync(MVCAQ.ServiceReferansimiz2.CevaplariGosterRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public MVCAQ.ServiceReferansimiz2.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MVCAQ.ServiceReferansimiz2.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVCAQ.ServiceReferansimiz2.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MVCAQ.ServiceReferansimiz2.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KaydolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Kaydol", Namespace="http://tempuri.org/", Order=0)]
        public MVCAQ.ServiceReferansimiz2.KaydolRequestBody Body;
        
        public KaydolRequest() {
        }
        
        public KaydolRequest(MVCAQ.ServiceReferansimiz2.KaydolRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KaydolRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVCAQ.ServiceReferansimiz2.Users u;
        
        public KaydolRequestBody() {
        }
        
        public KaydolRequestBody(MVCAQ.ServiceReferansimiz2.Users u) {
            this.u = u;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KaydolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KaydolResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVCAQ.ServiceReferansimiz2.KaydolResponseBody Body;
        
        public KaydolResponse() {
        }
        
        public KaydolResponse(MVCAQ.ServiceReferansimiz2.KaydolResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KaydolResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string KaydolResult;
        
        public KaydolResponseBody() {
        }
        
        public KaydolResponseBody(string KaydolResult) {
            this.KaydolResult = KaydolResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GirisYapRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GirisYap", Namespace="http://tempuri.org/", Order=0)]
        public MVCAQ.ServiceReferansimiz2.GirisYapRequestBody Body;
        
        public GirisYapRequest() {
        }
        
        public GirisYapRequest(MVCAQ.ServiceReferansimiz2.GirisYapRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GirisYapRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVCAQ.ServiceReferansimiz2.LoginData d;
        
        public GirisYapRequestBody() {
        }
        
        public GirisYapRequestBody(MVCAQ.ServiceReferansimiz2.LoginData d) {
            this.d = d;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GirisYapResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GirisYapResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVCAQ.ServiceReferansimiz2.GirisYapResponseBody Body;
        
        public GirisYapResponse() {
        }
        
        public GirisYapResponse(MVCAQ.ServiceReferansimiz2.GirisYapResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GirisYapResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVCAQ.ServiceReferansimiz2.Users GirisYapResult;
        
        public GirisYapResponseBody() {
        }
        
        public GirisYapResponseBody(MVCAQ.ServiceReferansimiz2.Users GirisYapResult) {
            this.GirisYapResult = GirisYapResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoruSorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SoruSor", Namespace="http://tempuri.org/", Order=0)]
        public MVCAQ.ServiceReferansimiz2.SoruSorRequestBody Body;
        
        public SoruSorRequest() {
        }
        
        public SoruSorRequest(MVCAQ.ServiceReferansimiz2.SoruSorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SoruSorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVCAQ.ServiceReferansimiz2.Questions q;
        
        public SoruSorRequestBody() {
        }
        
        public SoruSorRequestBody(MVCAQ.ServiceReferansimiz2.Questions q) {
            this.q = q;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoruSorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SoruSorResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVCAQ.ServiceReferansimiz2.SoruSorResponseBody Body;
        
        public SoruSorResponse() {
        }
        
        public SoruSorResponse(MVCAQ.ServiceReferansimiz2.SoruSorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SoruSorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SoruSorResult;
        
        public SoruSorResponseBody() {
        }
        
        public SoruSorResponseBody(string SoruSorResult) {
            this.SoruSorResult = SoruSorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoruSilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SoruSil", Namespace="http://tempuri.org/", Order=0)]
        public MVCAQ.ServiceReferansimiz2.SoruSilRequestBody Body;
        
        public SoruSilRequest() {
        }
        
        public SoruSilRequest(MVCAQ.ServiceReferansimiz2.SoruSilRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SoruSilRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public SoruSilRequestBody() {
        }
        
        public SoruSilRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoruSilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SoruSilResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVCAQ.ServiceReferansimiz2.SoruSilResponseBody Body;
        
        public SoruSilResponse() {
        }
        
        public SoruSilResponse(MVCAQ.ServiceReferansimiz2.SoruSilResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SoruSilResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SoruSilResult;
        
        public SoruSilResponseBody() {
        }
        
        public SoruSilResponseBody(string SoruSilResult) {
            this.SoruSilResult = SoruSilResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoruListeleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SoruListele", Namespace="http://tempuri.org/", Order=0)]
        public MVCAQ.ServiceReferansimiz2.SoruListeleRequestBody Body;
        
        public SoruListeleRequest() {
        }
        
        public SoruListeleRequest(MVCAQ.ServiceReferansimiz2.SoruListeleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SoruListeleRequestBody {
        
        public SoruListeleRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoruListeleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SoruListeleResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVCAQ.ServiceReferansimiz2.SoruListeleResponseBody Body;
        
        public SoruListeleResponse() {
        }
        
        public SoruListeleResponse(MVCAQ.ServiceReferansimiz2.SoruListeleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SoruListeleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVCAQ.ServiceReferansimiz2.Questions[] SoruListeleResult;
        
        public SoruListeleResponseBody() {
        }
        
        public SoruListeleResponseBody(MVCAQ.ServiceReferansimiz2.Questions[] SoruListeleResult) {
            this.SoruListeleResult = SoruListeleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoruAraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SoruAra", Namespace="http://tempuri.org/", Order=0)]
        public MVCAQ.ServiceReferansimiz2.SoruAraRequestBody Body;
        
        public SoruAraRequest() {
        }
        
        public SoruAraRequest(MVCAQ.ServiceReferansimiz2.SoruAraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SoruAraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string s;
        
        public SoruAraRequestBody() {
        }
        
        public SoruAraRequestBody(string s) {
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoruAraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SoruAraResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVCAQ.ServiceReferansimiz2.SoruAraResponseBody Body;
        
        public SoruAraResponse() {
        }
        
        public SoruAraResponse(MVCAQ.ServiceReferansimiz2.SoruAraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SoruAraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVCAQ.ServiceReferansimiz2.Questions[] SoruAraResult;
        
        public SoruAraResponseBody() {
        }
        
        public SoruAraResponseBody(MVCAQ.ServiceReferansimiz2.Questions[] SoruAraResult) {
            this.SoruAraResult = SoruAraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoruDuzenleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SoruDuzenle", Namespace="http://tempuri.org/", Order=0)]
        public MVCAQ.ServiceReferansimiz2.SoruDuzenleRequestBody Body;
        
        public SoruDuzenleRequest() {
        }
        
        public SoruDuzenleRequest(MVCAQ.ServiceReferansimiz2.SoruDuzenleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SoruDuzenleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVCAQ.ServiceReferansimiz2.Questions q;
        
        public SoruDuzenleRequestBody() {
        }
        
        public SoruDuzenleRequestBody(MVCAQ.ServiceReferansimiz2.Questions q) {
            this.q = q;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoruDuzenleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SoruDuzenleResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVCAQ.ServiceReferansimiz2.SoruDuzenleResponseBody Body;
        
        public SoruDuzenleResponse() {
        }
        
        public SoruDuzenleResponse(MVCAQ.ServiceReferansimiz2.SoruDuzenleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SoruDuzenleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SoruDuzenleResult;
        
        public SoruDuzenleResponseBody() {
        }
        
        public SoruDuzenleResponseBody(string SoruDuzenleResult) {
            this.SoruDuzenleResult = SoruDuzenleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoruCevaplaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SoruCevapla", Namespace="http://tempuri.org/", Order=0)]
        public MVCAQ.ServiceReferansimiz2.SoruCevaplaRequestBody Body;
        
        public SoruCevaplaRequest() {
        }
        
        public SoruCevaplaRequest(MVCAQ.ServiceReferansimiz2.SoruCevaplaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SoruCevaplaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVCAQ.ServiceReferansimiz2.QuestionAnswers q;
        
        public SoruCevaplaRequestBody() {
        }
        
        public SoruCevaplaRequestBody(MVCAQ.ServiceReferansimiz2.QuestionAnswers q) {
            this.q = q;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoruCevaplaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SoruCevaplaResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVCAQ.ServiceReferansimiz2.SoruCevaplaResponseBody Body;
        
        public SoruCevaplaResponse() {
        }
        
        public SoruCevaplaResponse(MVCAQ.ServiceReferansimiz2.SoruCevaplaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SoruCevaplaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SoruCevaplaResult;
        
        public SoruCevaplaResponseBody() {
        }
        
        public SoruCevaplaResponseBody(string SoruCevaplaResult) {
            this.SoruCevaplaResult = SoruCevaplaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CevaplariGosterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CevaplariGoster", Namespace="http://tempuri.org/", Order=0)]
        public MVCAQ.ServiceReferansimiz2.CevaplariGosterRequestBody Body;
        
        public CevaplariGosterRequest() {
        }
        
        public CevaplariGosterRequest(MVCAQ.ServiceReferansimiz2.CevaplariGosterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CevaplariGosterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public CevaplariGosterRequestBody() {
        }
        
        public CevaplariGosterRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CevaplariGosterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CevaplariGosterResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVCAQ.ServiceReferansimiz2.CevaplariGosterResponseBody Body;
        
        public CevaplariGosterResponse() {
        }
        
        public CevaplariGosterResponse(MVCAQ.ServiceReferansimiz2.CevaplariGosterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CevaplariGosterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVCAQ.ServiceReferansimiz2.QuestionAnswers[] CevaplariGosterResult;
        
        public CevaplariGosterResponseBody() {
        }
        
        public CevaplariGosterResponseBody(MVCAQ.ServiceReferansimiz2.QuestionAnswers[] CevaplariGosterResult) {
            this.CevaplariGosterResult = CevaplariGosterResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AQServiceSoapChannel : MVCAQ.ServiceReferansimiz2.AQServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AQServiceSoapClient : System.ServiceModel.ClientBase<MVCAQ.ServiceReferansimiz2.AQServiceSoap>, MVCAQ.ServiceReferansimiz2.AQServiceSoap {
        
        public AQServiceSoapClient() {
        }
        
        public AQServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AQServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AQServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AQServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCAQ.ServiceReferansimiz2.HelloWorldResponse MVCAQ.ServiceReferansimiz2.AQServiceSoap.HelloWorld(MVCAQ.ServiceReferansimiz2.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            MVCAQ.ServiceReferansimiz2.HelloWorldRequest inValue = new MVCAQ.ServiceReferansimiz2.HelloWorldRequest();
            inValue.Body = new MVCAQ.ServiceReferansimiz2.HelloWorldRequestBody();
            MVCAQ.ServiceReferansimiz2.HelloWorldResponse retVal = ((MVCAQ.ServiceReferansimiz2.AQServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.HelloWorldResponse> MVCAQ.ServiceReferansimiz2.AQServiceSoap.HelloWorldAsync(MVCAQ.ServiceReferansimiz2.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.HelloWorldResponse> HelloWorldAsync() {
            MVCAQ.ServiceReferansimiz2.HelloWorldRequest inValue = new MVCAQ.ServiceReferansimiz2.HelloWorldRequest();
            inValue.Body = new MVCAQ.ServiceReferansimiz2.HelloWorldRequestBody();
            return ((MVCAQ.ServiceReferansimiz2.AQServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCAQ.ServiceReferansimiz2.KaydolResponse MVCAQ.ServiceReferansimiz2.AQServiceSoap.Kaydol(MVCAQ.ServiceReferansimiz2.KaydolRequest request) {
            return base.Channel.Kaydol(request);
        }
        
        public string Kaydol(MVCAQ.ServiceReferansimiz2.Users u) {
            MVCAQ.ServiceReferansimiz2.KaydolRequest inValue = new MVCAQ.ServiceReferansimiz2.KaydolRequest();
            inValue.Body = new MVCAQ.ServiceReferansimiz2.KaydolRequestBody();
            inValue.Body.u = u;
            MVCAQ.ServiceReferansimiz2.KaydolResponse retVal = ((MVCAQ.ServiceReferansimiz2.AQServiceSoap)(this)).Kaydol(inValue);
            return retVal.Body.KaydolResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.KaydolResponse> MVCAQ.ServiceReferansimiz2.AQServiceSoap.KaydolAsync(MVCAQ.ServiceReferansimiz2.KaydolRequest request) {
            return base.Channel.KaydolAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.KaydolResponse> KaydolAsync(MVCAQ.ServiceReferansimiz2.Users u) {
            MVCAQ.ServiceReferansimiz2.KaydolRequest inValue = new MVCAQ.ServiceReferansimiz2.KaydolRequest();
            inValue.Body = new MVCAQ.ServiceReferansimiz2.KaydolRequestBody();
            inValue.Body.u = u;
            return ((MVCAQ.ServiceReferansimiz2.AQServiceSoap)(this)).KaydolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCAQ.ServiceReferansimiz2.GirisYapResponse MVCAQ.ServiceReferansimiz2.AQServiceSoap.GirisYap(MVCAQ.ServiceReferansimiz2.GirisYapRequest request) {
            return base.Channel.GirisYap(request);
        }
        
        public MVCAQ.ServiceReferansimiz2.Users GirisYap(MVCAQ.ServiceReferansimiz2.LoginData d) {
            MVCAQ.ServiceReferansimiz2.GirisYapRequest inValue = new MVCAQ.ServiceReferansimiz2.GirisYapRequest();
            inValue.Body = new MVCAQ.ServiceReferansimiz2.GirisYapRequestBody();
            inValue.Body.d = d;
            MVCAQ.ServiceReferansimiz2.GirisYapResponse retVal = ((MVCAQ.ServiceReferansimiz2.AQServiceSoap)(this)).GirisYap(inValue);
            return retVal.Body.GirisYapResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.GirisYapResponse> MVCAQ.ServiceReferansimiz2.AQServiceSoap.GirisYapAsync(MVCAQ.ServiceReferansimiz2.GirisYapRequest request) {
            return base.Channel.GirisYapAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.GirisYapResponse> GirisYapAsync(MVCAQ.ServiceReferansimiz2.LoginData d) {
            MVCAQ.ServiceReferansimiz2.GirisYapRequest inValue = new MVCAQ.ServiceReferansimiz2.GirisYapRequest();
            inValue.Body = new MVCAQ.ServiceReferansimiz2.GirisYapRequestBody();
            inValue.Body.d = d;
            return ((MVCAQ.ServiceReferansimiz2.AQServiceSoap)(this)).GirisYapAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCAQ.ServiceReferansimiz2.SoruSorResponse MVCAQ.ServiceReferansimiz2.AQServiceSoap.SoruSor(MVCAQ.ServiceReferansimiz2.SoruSorRequest request) {
            return base.Channel.SoruSor(request);
        }
        
        public string SoruSor(MVCAQ.ServiceReferansimiz2.Questions q) {
            MVCAQ.ServiceReferansimiz2.SoruSorRequest inValue = new MVCAQ.ServiceReferansimiz2.SoruSorRequest();
            inValue.Body = new MVCAQ.ServiceReferansimiz2.SoruSorRequestBody();
            inValue.Body.q = q;
            MVCAQ.ServiceReferansimiz2.SoruSorResponse retVal = ((MVCAQ.ServiceReferansimiz2.AQServiceSoap)(this)).SoruSor(inValue);
            return retVal.Body.SoruSorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.SoruSorResponse> MVCAQ.ServiceReferansimiz2.AQServiceSoap.SoruSorAsync(MVCAQ.ServiceReferansimiz2.SoruSorRequest request) {
            return base.Channel.SoruSorAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.SoruSorResponse> SoruSorAsync(MVCAQ.ServiceReferansimiz2.Questions q) {
            MVCAQ.ServiceReferansimiz2.SoruSorRequest inValue = new MVCAQ.ServiceReferansimiz2.SoruSorRequest();
            inValue.Body = new MVCAQ.ServiceReferansimiz2.SoruSorRequestBody();
            inValue.Body.q = q;
            return ((MVCAQ.ServiceReferansimiz2.AQServiceSoap)(this)).SoruSorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCAQ.ServiceReferansimiz2.SoruSilResponse MVCAQ.ServiceReferansimiz2.AQServiceSoap.SoruSil(MVCAQ.ServiceReferansimiz2.SoruSilRequest request) {
            return base.Channel.SoruSil(request);
        }
        
        public string SoruSil(int id) {
            MVCAQ.ServiceReferansimiz2.SoruSilRequest inValue = new MVCAQ.ServiceReferansimiz2.SoruSilRequest();
            inValue.Body = new MVCAQ.ServiceReferansimiz2.SoruSilRequestBody();
            inValue.Body.id = id;
            MVCAQ.ServiceReferansimiz2.SoruSilResponse retVal = ((MVCAQ.ServiceReferansimiz2.AQServiceSoap)(this)).SoruSil(inValue);
            return retVal.Body.SoruSilResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.SoruSilResponse> MVCAQ.ServiceReferansimiz2.AQServiceSoap.SoruSilAsync(MVCAQ.ServiceReferansimiz2.SoruSilRequest request) {
            return base.Channel.SoruSilAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.SoruSilResponse> SoruSilAsync(int id) {
            MVCAQ.ServiceReferansimiz2.SoruSilRequest inValue = new MVCAQ.ServiceReferansimiz2.SoruSilRequest();
            inValue.Body = new MVCAQ.ServiceReferansimiz2.SoruSilRequestBody();
            inValue.Body.id = id;
            return ((MVCAQ.ServiceReferansimiz2.AQServiceSoap)(this)).SoruSilAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCAQ.ServiceReferansimiz2.SoruListeleResponse MVCAQ.ServiceReferansimiz2.AQServiceSoap.SoruListele(MVCAQ.ServiceReferansimiz2.SoruListeleRequest request) {
            return base.Channel.SoruListele(request);
        }
        
        public MVCAQ.ServiceReferansimiz2.Questions[] SoruListele() {
            MVCAQ.ServiceReferansimiz2.SoruListeleRequest inValue = new MVCAQ.ServiceReferansimiz2.SoruListeleRequest();
            inValue.Body = new MVCAQ.ServiceReferansimiz2.SoruListeleRequestBody();
            MVCAQ.ServiceReferansimiz2.SoruListeleResponse retVal = ((MVCAQ.ServiceReferansimiz2.AQServiceSoap)(this)).SoruListele(inValue);
            return retVal.Body.SoruListeleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.SoruListeleResponse> MVCAQ.ServiceReferansimiz2.AQServiceSoap.SoruListeleAsync(MVCAQ.ServiceReferansimiz2.SoruListeleRequest request) {
            return base.Channel.SoruListeleAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.SoruListeleResponse> SoruListeleAsync() {
            MVCAQ.ServiceReferansimiz2.SoruListeleRequest inValue = new MVCAQ.ServiceReferansimiz2.SoruListeleRequest();
            inValue.Body = new MVCAQ.ServiceReferansimiz2.SoruListeleRequestBody();
            return ((MVCAQ.ServiceReferansimiz2.AQServiceSoap)(this)).SoruListeleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCAQ.ServiceReferansimiz2.SoruAraResponse MVCAQ.ServiceReferansimiz2.AQServiceSoap.SoruAra(MVCAQ.ServiceReferansimiz2.SoruAraRequest request) {
            return base.Channel.SoruAra(request);
        }
        
        public MVCAQ.ServiceReferansimiz2.Questions[] SoruAra(string s) {
            MVCAQ.ServiceReferansimiz2.SoruAraRequest inValue = new MVCAQ.ServiceReferansimiz2.SoruAraRequest();
            inValue.Body = new MVCAQ.ServiceReferansimiz2.SoruAraRequestBody();
            inValue.Body.s = s;
            MVCAQ.ServiceReferansimiz2.SoruAraResponse retVal = ((MVCAQ.ServiceReferansimiz2.AQServiceSoap)(this)).SoruAra(inValue);
            return retVal.Body.SoruAraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.SoruAraResponse> MVCAQ.ServiceReferansimiz2.AQServiceSoap.SoruAraAsync(MVCAQ.ServiceReferansimiz2.SoruAraRequest request) {
            return base.Channel.SoruAraAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.SoruAraResponse> SoruAraAsync(string s) {
            MVCAQ.ServiceReferansimiz2.SoruAraRequest inValue = new MVCAQ.ServiceReferansimiz2.SoruAraRequest();
            inValue.Body = new MVCAQ.ServiceReferansimiz2.SoruAraRequestBody();
            inValue.Body.s = s;
            return ((MVCAQ.ServiceReferansimiz2.AQServiceSoap)(this)).SoruAraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCAQ.ServiceReferansimiz2.SoruDuzenleResponse MVCAQ.ServiceReferansimiz2.AQServiceSoap.SoruDuzenle(MVCAQ.ServiceReferansimiz2.SoruDuzenleRequest request) {
            return base.Channel.SoruDuzenle(request);
        }
        
        public string SoruDuzenle(MVCAQ.ServiceReferansimiz2.Questions q) {
            MVCAQ.ServiceReferansimiz2.SoruDuzenleRequest inValue = new MVCAQ.ServiceReferansimiz2.SoruDuzenleRequest();
            inValue.Body = new MVCAQ.ServiceReferansimiz2.SoruDuzenleRequestBody();
            inValue.Body.q = q;
            MVCAQ.ServiceReferansimiz2.SoruDuzenleResponse retVal = ((MVCAQ.ServiceReferansimiz2.AQServiceSoap)(this)).SoruDuzenle(inValue);
            return retVal.Body.SoruDuzenleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.SoruDuzenleResponse> MVCAQ.ServiceReferansimiz2.AQServiceSoap.SoruDuzenleAsync(MVCAQ.ServiceReferansimiz2.SoruDuzenleRequest request) {
            return base.Channel.SoruDuzenleAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.SoruDuzenleResponse> SoruDuzenleAsync(MVCAQ.ServiceReferansimiz2.Questions q) {
            MVCAQ.ServiceReferansimiz2.SoruDuzenleRequest inValue = new MVCAQ.ServiceReferansimiz2.SoruDuzenleRequest();
            inValue.Body = new MVCAQ.ServiceReferansimiz2.SoruDuzenleRequestBody();
            inValue.Body.q = q;
            return ((MVCAQ.ServiceReferansimiz2.AQServiceSoap)(this)).SoruDuzenleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCAQ.ServiceReferansimiz2.SoruCevaplaResponse MVCAQ.ServiceReferansimiz2.AQServiceSoap.SoruCevapla(MVCAQ.ServiceReferansimiz2.SoruCevaplaRequest request) {
            return base.Channel.SoruCevapla(request);
        }
        
        public string SoruCevapla(MVCAQ.ServiceReferansimiz2.QuestionAnswers q) {
            MVCAQ.ServiceReferansimiz2.SoruCevaplaRequest inValue = new MVCAQ.ServiceReferansimiz2.SoruCevaplaRequest();
            inValue.Body = new MVCAQ.ServiceReferansimiz2.SoruCevaplaRequestBody();
            inValue.Body.q = q;
            MVCAQ.ServiceReferansimiz2.SoruCevaplaResponse retVal = ((MVCAQ.ServiceReferansimiz2.AQServiceSoap)(this)).SoruCevapla(inValue);
            return retVal.Body.SoruCevaplaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.SoruCevaplaResponse> MVCAQ.ServiceReferansimiz2.AQServiceSoap.SoruCevaplaAsync(MVCAQ.ServiceReferansimiz2.SoruCevaplaRequest request) {
            return base.Channel.SoruCevaplaAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.SoruCevaplaResponse> SoruCevaplaAsync(MVCAQ.ServiceReferansimiz2.QuestionAnswers q) {
            MVCAQ.ServiceReferansimiz2.SoruCevaplaRequest inValue = new MVCAQ.ServiceReferansimiz2.SoruCevaplaRequest();
            inValue.Body = new MVCAQ.ServiceReferansimiz2.SoruCevaplaRequestBody();
            inValue.Body.q = q;
            return ((MVCAQ.ServiceReferansimiz2.AQServiceSoap)(this)).SoruCevaplaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVCAQ.ServiceReferansimiz2.CevaplariGosterResponse MVCAQ.ServiceReferansimiz2.AQServiceSoap.CevaplariGoster(MVCAQ.ServiceReferansimiz2.CevaplariGosterRequest request) {
            return base.Channel.CevaplariGoster(request);
        }
        
        public MVCAQ.ServiceReferansimiz2.QuestionAnswers[] CevaplariGoster(int id) {
            MVCAQ.ServiceReferansimiz2.CevaplariGosterRequest inValue = new MVCAQ.ServiceReferansimiz2.CevaplariGosterRequest();
            inValue.Body = new MVCAQ.ServiceReferansimiz2.CevaplariGosterRequestBody();
            inValue.Body.id = id;
            MVCAQ.ServiceReferansimiz2.CevaplariGosterResponse retVal = ((MVCAQ.ServiceReferansimiz2.AQServiceSoap)(this)).CevaplariGoster(inValue);
            return retVal.Body.CevaplariGosterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.CevaplariGosterResponse> MVCAQ.ServiceReferansimiz2.AQServiceSoap.CevaplariGosterAsync(MVCAQ.ServiceReferansimiz2.CevaplariGosterRequest request) {
            return base.Channel.CevaplariGosterAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVCAQ.ServiceReferansimiz2.CevaplariGosterResponse> CevaplariGosterAsync(int id) {
            MVCAQ.ServiceReferansimiz2.CevaplariGosterRequest inValue = new MVCAQ.ServiceReferansimiz2.CevaplariGosterRequest();
            inValue.Body = new MVCAQ.ServiceReferansimiz2.CevaplariGosterRequestBody();
            inValue.Body.id = id;
            return ((MVCAQ.ServiceReferansimiz2.AQServiceSoap)(this)).CevaplariGosterAsync(inValue);
        }
    }
}
